# Generated by Django 2.1.1 on 2018-09-17 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='이름')),
                ('image', models.ImageField(blank=True, upload_to='image/', verbose_name='사진')),
            ],
        ),
        migrations.CreateModel(
            name='Circle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='동아리명')),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50, verbose_name='작가')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('poster', models.ImageField(blank=True, upload_to='poster/', verbose_name='포스터')),
                ('running_time', models.TimeField(verbose_name='러닝타임')),
                ('date', models.DateTimeField(verbose_name='공연날짜')),
                ('place', models.CharField(max_length=300, verbose_name='공연장소')),
                ('cast_set', models.ManyToManyField(blank=True, to='petter.Cast')),
                ('circle', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='petter.Circle')),
            ],
        ),
    ]
