# Generated by Django 2.1.1 on 2018-09-17 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petter', '0002_auto_20180917_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='price',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='가격'),
        ),
        migrations.AddField(
            model_name='show',
            name='summary',
            field=models.TextField(blank=True, null=True, verbose_name='내용설명'),
        ),
    ]
